name: format_dart_imports
description: A sample command-line application.
version: 0.0.6

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  process_run: ^0.12.3+2
  import_sorter: ^4.6.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
